sudo: required
services:
- docker

env:
  matrix:
  - JOB_ARCH=amd64
  - JOB_ARCH=arm64
  - JOB_ARCH=armel
  - JOB_ARCH=armhf
  - JOB_ARCH=i386
  - JOB_ARCH=mips
  - JOB_ARCH=mips64el
  - JOB_ARCH=mipsel
  - JOB_ARCH=ppc64el
  - JOB_ARCH=s390x

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get --yes install docker-ce

script:
- ./update.sh ${TRAVIS_BRANCH}
- docker build -t laarid/cross-build:${TRAVIS_BRANCH}-${JOB_ARCH} ${JOB_ARCH}
- docker images

notifications:
  slack:
    rooms:
    - secure: "Nc5t1c1oCEILiyYYQly9A6IgAgPyv/AL3kjeO42rYYP/tEXdGc2h2ugAqIKLmwHS+XMJkpZ3n/drXo9XaweY7h0jvR1aZqMpHHEikzgdwKsHItcPhwmweruffLU/iGTnQHJOe74Eiw+VoaJnByW1vUxjFDw/M5ex+1qpSPSBNgfBQlxxTO4NWD69WrYi6BMqxsYcYUqC1ioT8zTSMkZ4cWjZEEnJoXYaoFT51gcGBaRHgY2HV6e/9Gpmb3DPGZXXB2pbrNa7G/UofIS/2GJi+NdmPJyAwcmhIdzafpsXd1wotEHIaytSNVbQUFdBcuse1WCOQ3CnzyWYgltkRdZGCBhftjht9p5YmPDSONbAMVP5yQwOCXcQuj7BQS4VxIF1JXsKW1Gg2r/2yuDwp/duCiwKUYdn6eb2/pAlrwuNHa4sHmmRj3+j+23X3XJptCYraLrV3p3LIFXr8/2wdw491lcTknw3mIcMLivASchTb5bzrT6qKOeLdIhr4BJ736Swkkv36S4ChMhuEI7qbbZY3IMxOau7zkThV0kM3kjPCWtugaJIH5KyUccDvFog4Jt8aVQMxZQivY4jAz4MHT4Gyb+1uTcYU0wGqTtYxDamCFnKuY8U/lMDH9LtjOfcIWUhLHjX+0/oM6gO1eBw/bUsQwH/avhfSpsVpyhQXxKDIxs="
